theme: jekyll-theme-minimal
title: [Tzvetomir Tzvetanov’s github web page]
description: [Here you can find some descriptions of work related stuff and links to code posted “AS IS” (see the related license posted with the code).]
